### ISSUE TITLE
Instructions in readme doesn't work out of the box

### ISSUE THREAD

**Issue by Kecksdose** [bixel/coffee#1]
Hi Kevin,

I tried to set up the coffeeserver as suggested in your README. Unfortunately it doesn't work for me. 

First, I needed to set `SECRET_KEY` to a specific value, e.g.

    COFFEE_DEBUG=True COFFEE_LDAP=False COFFEE_SECRET_KEY="super_secret" python coffee.py

Afterwards, I received the error: 

    AttributeError: 'AnonymousUserMixin' object has no attribute 'username'

in line 108 of coffee.py, which is here:

    def guest_required(f):
        @wraps(f)
        def decorated_function(*args, **kwargs):
            if current_user.username == 'guest' or app.config['DEBUG']:
                return f(*args, **kwargs)
            else:
                abort(403)
        return decorated_function

Can you help me?

**Comment by bixel** [comment]
Yep, absolutely, I didn't think of empty databases. It should work now. Also thanks for the secret key hint, I adjusted that default 👍 ❤️
